### PR TITLE
Fix AddDefaultEndpointSelectorPolicy

### PR DESCRIPTION
**Pull request by Shane32**
Fixes:
- #705

### CODE REVIEW

**Comment by Shane32** [comment]
There is no logical reason to need `TryAddEnumerable` support.  Of course someone could call `AddDefaultEndpointSelectorPolicy` twice, which would cause a problem, but then they could also call `AddDocumentListener<T>` or `AddMiddleware<T>` twice also, which would also be a problem.  Perhaps there will be a time when we need support for `TryAddEnumerable`, but I do not think we need to do so now.

**Comment by Shane32** [comment]
Note that Autofac very likely does not support `TryAddEnumerable`.  I know it does not support `Register` with `replace = true`, which is similar in concept, and we will simply have to ignore the `replace` parameter there (which should be fine).  Ideally we would remove the `replace` parameter and write the code such that it is not needed, for more compatibility with any DI engine.

**Comment by sungam3r** [comment]
I suggest to merge #2946 and keep `TryRegister` to be more explicit.

**Comment by sungam3r** [comment]
> Note that Autofac very likely does not support TryAddEnumerable.

When I worked on https://github.com/EasyNetQ/EasyNetQ/pull/1108 I was very necessary for the advice regarding Autofac. After a couple of days attempts to force all providers to work the same, I came to the conclusion that it is impossible.

**Comment by sungam3r** [comment]
#730

**Pull request closed without merging**
