### PR TITLE
Add ReusableMemoryReaderStream class

### PR DESCRIPTION
**Pull request by Shane32**
This is an optimization for deserializing JSON messages for WebSocket support.

In the message loop, WebSocket messages are read into a buffer (byte array), and then can be read by the installed GraphQL.NET serialization engine.  However, the serializer only accepts streams, not byte arrays with offset & length.  So while we could create a memory stream for each message, this would cause an allocation for each message (the MemoryStream itself), even if the actual memory data was not copied (which it might be; can't remember).

Note that we cannot use MemoryStream with GetBuffer because the JSON deserializer will throw an exception saying that data exists after the end of the JSON data.  It must encounter the end of the stream to properly deserialize.

So this class maps to a buffer and can be reset to Position 0 with a settable length depending on the length of the message received.

### CODE REVIEW

**Comment by Shane32** [comment]
@sungam3r This is ready for review; please post an ETA when you get a chance.

**Comment by sungam3r** [comment]
I'll review this one and other PRs that evening.

**Review by sungam3r — APPROVED** [review]
Did you consider https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream ?

**Comment by sungam3r** [comment]
Regarding my promise https://github.com/graphql-dotnet/server/pull/805#issuecomment-1139421420 - unfortunately, I didn’t have time. I will have a few hours tomorrow morning (since 6 AM) to carefully review everything left.

**Comment by Shane32** [comment]
> Regarding my promise [#805 (comment)](https://github.com/graphql-dotnet/server/pull/805#issuecomment-1139421420) - unfortunately, I didn’t have time. I will have a few hours tomorrow morning (since 6 AM) to carefully review everything left.

No problem. I was really just asking for an ETA on the other outstanding PRs to help manage expectations.

**Comment by Shane32** [comment]
> Did you consider https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream ?

No, but thanks for the link - I’ll review. It may be useful when the WebSocket message does not fit in the preallocated buffer.

**Comment by sungam3r** [comment]
I use `RecyclableMemoryStream` in some services in production. This is a fairly simple concept and detailed documentation is written for the project.

**Pull request merged**
