### PR TITLE
Update parser

### PR DESCRIPTION
**Pull request by sungam3r**
Bumps GraphQL.NET with new parser API.

@Shane32 Please go on and rewrite serializer from server project. You knows better what to change here for new serialization API.

### CODE REVIEW

**Comment by Shane32** [comment]
Yes I will within a few days; just wanted to dump the obsolete stuff first and saw you had a PR already.

**Review by Shane32 — APPROVED** [review]

**Comment by sungam3r** [comment]
This PR is not ready, two compilation errors left. I did not dare to change serialization code myself. I would spend more time then you making it.

**Comment by Shane32** [comment]
Oh does it need to be fixed in order to merge this PR?  I would expect that we should be able to merge and update serialization in a separate PR.

**Comment by sungam3r** [comment]
изображение

**Comment by sungam3r** [comment]
I'm done for today.

**Comment by Shane32** [comment]
needs at least one more change.  After merged I'll redo serialization support in another PR

**Comment by sungam3r** [comment]
Thanks.

**Comment by sungam3r** [comment]
#715

**Pull request merged**
