### PR TITLE
Merge branch 'master' into develop

### PR DESCRIPTION
**Pull request by sungam3r**
# Conflicts:
#	samples/Samples.Server/Samples.Server.csproj
#	samples/Samples.Server/Startup.cs
#	samples/Samples.Server/StartupWithRouting.cs
#	src/Transports.Subscriptions.Abstractions/SubscriptionManager.cs
#	src/Transports.Subscriptions.WebSockets/WebSocketConnectionFactory.cs
#	tests/ApiApprovalTests/GraphQL.Server.Transports.Subscriptions.WebSockets.approved.txt

### CODE REVIEW

**Comment by Shane32** [comment]
You can't make PRs to merge master into develop.  If you look at the branch history, git still doesn't think develop has master merged in.  You have to do so manually.  I'll fix it.

**Comment by Shane32** [comment]
Fixed.

**Comment by Shane32** [comment]
Test run: https://github.com/graphql-dotnet/server/actions/runs/1841604164

**Comment by sungam3r** [comment]
I did this PR only to look into diff, I didn't merge it. Then I pushed changes into develop. GitHub shows like PR was merged though.

**Comment by Shane32** [comment]
Yeah, not sure what happened.  I did notice it wasn't "squash and merged" like if it was merged through the website.  But git still didn't recognize that it was a merge commit and attempting to merge with master still showed a lot of conflicts.  All good now anyway.

**Pull request merged**
