### PR TITLE
fix for http get support

### PR DESCRIPTION
**Pull request by OneCyrus**
PR #84 broke HTTP GET support. instead of disabling HTTP GET, which is defined by the graphql specs, this PR fixes the null exception when handling variables parsing.

### CODE REVIEW

**Comment by SimonCropp** [comment]
@OneCyrus is it possible to add a test to verify GET support so it doesnt break again in the future?

**Comment by OneCyrus** [comment]
sure, but there's no test project at all for transports.

**Comment by OneCyrus** [comment]
btw. issue is already fixed with #128 

though a proper test project wouldn't be too bad.

**Comment by cyberhck** [comment]
I'm seeing that GET is broken currently unfortunately, for some reason when browser tries to perform a GET request for websocket, this gets involved and throws an exception,
image

**Comment by sungam3r** [comment]
It's rather old PR. Current status of code is that middleware supports both GET and POST. See https://github.com/graphql-dotnet/server/blob/master/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L16-L27 and https://github.com/graphql-dotnet/server/blob/master/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L16-L27

Exception from https://github.com/graphql-dotnet/server/pull/130#issuecomment-787506352 has lready been fixed an will be released in v5.1 soon (days).

**Pull request closed without merging**
