### PR TITLE
Rename GraphQLBuilderExtensions to GraphQLAuthorizationBuilderExtensions

### LINKED ISSUE #456: GraphQL.Server.GraphQLBuilderExtensions class is defined multiple times in different assemblies
[GraphQL.Server.GraphQLBuilderExtensions in GraphQL.Sever.Authorization.AspNetCore assembly](https://github.com/graphql-dotnet/server/blob/master/src/Authorization.AspNetCore/GraphQLBuilderExtensions.cs)
[GraphQL.Server.GraphQLBuilderExtensions in GraphQL.Sever.Core assembly](https://github.com/graphql-dotnet/server/blob/master/src/Core/GraphQLBuilderExtensions.cs)

This may be the cause of some issues such as in #353 because it becomes near impossible to reference methods from both.

### PR DESCRIPTION
**Pull request by infogulch**
Fixes #456

### CODE REVIEW

**Comment by sungam3r** [comment]
You renamed only file name.

**Comment by infogulch** [comment]
Oops

**Comment by infogulch** [comment]
I accidentally clicked close, then I tried to rebase and lost my changes, then I committed with the wrong email.  Sorry!  These should be fixed now.

**Comment by infogulch** [comment]
Ok github doesn't like this PR anymore.  I opened a new one at #461

**Pull request closed without merging**
