### PR TITLE
Support for batches

### PR DESCRIPTION
**Pull request by sungam3r**
Fixes graphql-dotnet/graphql-dotnet#1128

### CODE REVIEW

**Comment by sungam3r** [comment]
Backward compatibility is maintained. It seems to be quite simple. @joemcbride Is there any specification violation?

**Comment by sungam3r** [comment]
https://blog.apollographql.com/query-batching-in-apollo-63acfd859862

**Comment by sungam3r** [comment]
@joemcbride I find it somewhat burdensome to require a `graphql-batch` (or any other) header from the client. Probably worth checking for an array - `[`?

**Comment by sungam3r** [comment]
Relates to graphql-dotnet/graphql-client#68

**Comment by joemcbride** [comment]
> Probably worth checking for an array - [?

That is probably the most sure way to check.  It is probably a little less performant since you would deserialize to string first, but that is probably acceptable.

**Comment by sungam3r** [comment]
> It is probably a little less performant since you would deserialize to string first

No premature string allocation, `StreamReader.Peek()` to the rescue. Also no more allocating `JsonSerializer` on each request.

**Pull request merged**
