### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by Shane32**
I suggest adding a MIT license to the repository -- see #593 

What names should be included?  As of now it matches the nuget package with Pekka Heikura only.  @pekkah are you okay with the addition of this license?  @sungam3r has also made a lot of commits and is the principal maintainer of the repository now.  I suggest adding him as well.

https://github.com/graphql-dotnet/server/graphs/contributors

### CODE REVIEW

**Comment by pekkah** [comment]
Copyright does not mean same as author/ contributor. Usual it is just used to assert the legal rights of the originator. Feel free to add more names or create an contributors file.

**Comment by Shane32** [comment]
I added @sungam3r .  @pekkah  if you can approve this PR, that would be great - thanks!

**Review by pekkah — APPROVED** [review]

**Comment by Shane32** [comment]
@sungam3r if you would like to approve this also, I'll merge it in.  Thanks!

**Comment by Shane32** [comment]
Ping @sungam3r

**Comment by Shane32** [comment]
As @sungam3r has not responded, I will remove his name from the copyright notice and merge this PR.

**Comment by sungam3r** [comment]
Hi guys! Justs returned back to OSS after a long break. I'm OK with all chenges, just reviewed after ~4 months :)

**Pull request merged**
