### PR TITLE
Introduce GraphQLHttpMiddleware.HandleRequest and switch to IMiddleware

### PR DESCRIPTION
**Pull request by sungam3r**
Allows to override response handling/writing, for example if one wants to proxy request.

### CODE REVIEW

**Comment by sungam3r** [comment]
@Shane32 I would like to merge this ASAP. At work we have special GraphQL proxy called "Security Proxy" that handles all GraphQL requests to real services. In order to do so we use source code from server project with some modified bits. This PR allows us to switch to "standard" middleware and remove all copied code keeping only `HandleRequest` bits.

**Comment by Shane32** [comment]
Makes sense but can we have the protected method just run the code inside the loop, which deduplicates code?

**Comment by Shane32** [comment]
I guess I’m just saying, sure, but we should have a few more protected methods here, to allow overriding various bits, not just one. InvokeAsync is still too long and not virtual.  I should probably look at my code and see what functionality I would need as a virtual method in order to derive from and use the stock middleware. I’m fine if you want to merge this today though.

**Comment by sungam3r** [comment]
I added `IMiddleware` as you did it GraphQL.NET example. It requires DI registrations now but middleware can be singleton.

**Comment by sungam3r** [comment]
Regarding loop - both branches are rather small and differ a bit. I would not try to merge them into one virtual method, as least for now.

**Comment by Shane32** [comment]
I see you made some new extension methods. Don’t we already have AddMiddleware methods? I would call these new ones AddHttpMiddleware and AddWebsocketsHttpMiddleware to eliminate confusion. Further, I think they are actually optional. We may want to see if, without these methods, the middleware gets instantiated every call or acts as a singleton. Or if they need to be registered.  Note that behavior may be different with the change to use IMiddleware.

**Comment by sungam3r** [comment]
> We may want to see if, without these methods, the middleware gets instantiated every call or acts as a singleton. 

After switching for `IMiddleware` registration in DI is `required**.

**Comment by Shane32** [comment]
I think we should rename the methods though. AddGraphQL.AddMiddleware implies GraphQL middleware not http middleware.

**Comment by sungam3r** [comment]
renamed

**Comment by sungam3r** [comment]
OK to merge?

**Review by Shane32 — APPROVED** [review]

**Pull request merged**
