### PR TITLE
Fix content-type bug

### PR DESCRIPTION
**Pull request by sungam3r**
I checked all middlewares in Firefox first. Then I noticed that Playground doesn't work in Chrome. See comments.

### CODE REVIEW

**Comment by sungam3r** [comment]
I think that it should be released as 5.1 - just recreate a tag after regenerating nuget token.

**Review by Shane32 — APPROVED** [review]

**Comment by basvandriel** [comment]
This still seems to be an issue. Any update on here?

**Comment by Shane32** [comment]
You downloaded version 5.1.0 (released yesterday) and still having an issue @basvandriel  ?

**Comment by basvandriel** [comment]
Yeah! I still get the content-type bug and the 2 prefixed headers.

**Comment by sungam3r** [comment]
Unfortunately this commit is not included in v5.1.0

**Comment by sungam3r** [comment]
Wait a bit. I'll release v5.1.1.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server/releases/tag/5.1.1

**Comment by basvandriel** [comment]
Did the job! Why is there a default` "Accept": "application/json"` though? Is it nessacery? @sungam3r

**Comment by sungam3r** [comment]
I don't know: https://github.com/graphql-dotnet/server/blob/master/src/Ui.Playground/Internal/PlaygroundPageModel.cs#L30

**Pull request merged**
