### PR TITLE
UI customization

### LINKED ISSUE #589: GraphiQL: support custom index page
We want to modify GraphiQL UI to add user authentication - this is easily done by customizing GraphiQL React components in index.html file.

It would be nice to be able to set custom index.html with additional data model in `GraphiQLOptions` for GraphiQL customization.

I have a small PR to add that support 🙌

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #589, rewrite of #590

### CODE REVIEW

**Comment by sungam3r** [comment]
@Shane32 I need your help in review this PR and some other stuff. I want to release v5.1, closing pending issues and go on will other work in this repo.

**Review by Shane32 — APPROVED** [review]
@sungam3r I'm good with the changes here.  (I'm assuming you tested the code and it works, etc.)

**Comment by Shane32** [comment]
> @Shane32 I need your help in review this PR and some other stuff. I want to release v5.1, closing pending issues and go on will other work in this repo.

Sure, I'll be happy to review any PRs you'd like me to.

**Comment by sungam3r** [comment]
This week I will try to review several PRs. Most likely, there will be related changes to check.

**Comment by sungam3r** [comment]
Now I was engaged in this project, because it is easier for me. GraphQL.NET changes are much larger and I will have more time to check them.

**Pull request merged**
