### PR TITLE
fix readme

### LINKED ISSUE #336: GraphQL.Server.Serialization.SystemTextJson not find in NuGet
.NET Core 3+:
dotnet add package GraphQL.Server.Serialization.SystemTextJson

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #336

### CODE REVIEW

**Comment by mrerhuo** [comment]
now this is GraphQL.Server.Transports.AspNetCore.SystemTextJson is import error please test new .net core 3.1 project.

**Comment by sungam3r** [comment]
`dotnet add package GraphQL.Server.Transports.AspNetCore.SystemTextJson --version 3.5.0-alpha0046` works well. There is no stable version (yet).

**Comment by sungam3r** [comment]
Readme.md was updated.

**Comment by benmccallum** [comment]
Ah crap. Went back and fwd on the name and didn't get all the spots. Thanks! I think we were suffering PR fatigue :P

The name is long, but it highlights that it depends on the aspnetcore part so I think it makes sense.

**Pull request merged**
