### PR TITLE
Remove non-authorization libraries, bump GraphQL to 5.0.0

### PR DESCRIPTION
**Pull request by Shane32**
Targets 'auth' branch.

- Removed other projects
- Updated build and test workflows to run against auth branch
- Bump GraphQL dependency to 5.0.0

### CODE REVIEW

**Comment by Shane32** [comment]
Once merged, this is ready to release the auth package version 6.0.0

**Comment by sungam3r** [comment]
You could minimize diff by only excluding projects from sln. There is no need to actually delete all files.

**Comment by Shane32** [comment]
Closing in favor of GraphQL.AspNetCore3 or updated server project

**Comment by sungam3r** [comment]
That is, you just did not have time to publish the package?

**Comment by Shane32** [comment]
Well, I thought you wanted to promptly release server v6, so there would be no point to this.  Second, I added auth to my library, so this is unnecessary for anyone using my repo.

If you like, I can issue the release...  sorta depends what the goal is for the server project.

**Comment by sungam3r** [comment]
So with v6 we'll publish all in one.

**Pull request closed without merging**
