### PR TITLE
Document that AddServer is legacy.

### PR DESCRIPTION
**Pull request by breyed**

### CODE REVIEW

**Comment by Shane32** [comment]
I don't think `AddServer()` is valid at all anymore, is it?  And this library doesn't support prior versions of .NET so we should probably just remove that line in the readme.

**Comment by breyed** [comment]
Makes sense to me. It may make onboarding easiest for most people if the readme used the new minimal hosting model in ASP.NET Core 6.0 as a baseline. Instructions for older frameworks could be included as annotations (perhaps in another section to keep the main onboarding lean).

**Comment by sungam3r** [comment]
`AddServer` method was removed in v6 so I would remove line from readme.

**Comment by sungam3r** [comment]
Fixed in #831

**Pull request closed without merging**
