### PR TITLE
Federated tracing support

### PR DESCRIPTION
**Pull request by nur858**
added GraphQLHttpRequestExtensions  to check if federated tracing support is enabled through http header

### CODE REVIEW

**Review by pekkah — APPROVED** [review]

**Comment by nur858** [comment]
Hi @pekkah I am not sure what to do here regarding these two checks (buildcheck, check-title). info here is not helpful to understand what's going on. 

thanks,

**Comment by Shane32** [comment]
@nur858 Can you merge from `develop` and re-run the tests to regenerate the api approvals?

**Comment by sungam3r** [comment]
How it works at all?

**Comment by Shane32** [comment]
Replaced by #894 (same code but with merge conflicts resolved, etc)

**Pull request closed without merging**
