### PR TITLE
Multi-TFM approvals

### PR DESCRIPTION
**Pull request by sungam3r**
Waiting for #665

### CODE REVIEW

**Comment by Shane32** [comment]
The code seems to be working fairly well in the GraphQL.NET project.  One thing: right now when one TFM fails, it won't run the other TFM check.  So it is necessary to run the api tests, rename the one file, and then run the tests again and rename the other file.  Can we have it compare/update both files before returning a failure to the test?  For example, start two tasks with Task.Run and then after a WhenAll then await one and the other or something?

**Comment by sungam3r** [comment]
> One thing: right now when one TFM fails, it won't run the other TFM check. 

I know 😄 . Already thought about it.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/pull/2818

**Comment by sungam3r** [comment]
Ported from GraphQL.NET

**Review by Shane32 — APPROVED** [review]

**Pull request merged**
