### PR TITLE
Fixing path string issue for playground schema fetch

### PR DESCRIPTION
**Pull request by pobisw**
Fix for #184 
Fix to consider path string for creation of graphql schema endpoint in playground

### CODE REVIEW

**Comment by BenjaBobs** [comment]
Is this also a problem for GraphiQL?

**Comment by pobisw** [comment]
> Is this also a problem for GraphiQL?

Yeah you are right, the url is extracted in the same way in GraphIql as well 

`fetch(window.location.protocol + "//" + window.location.host + '@Model.GraphQLEndPoint', {
				method: 'post',
				headers: {
					'Accept': 'application/json',
					'Content-Type': 'application/json',
				}`

**Comment by BenjaBobs** [comment]
I suspect it's also the case for Voyager. Maybe there should be a common way to access the full api url.

**Comment by pobisw** [comment]
> I suspect it's also the case for Voyager. Maybe there should be a common way to access the full api url.

yes it's the same code everywhere, let try to make 

> Hmm the commit history looks bit messy
Any Idea what went wrong ?

**Comment by pekkah** [comment]
Hmm I think you created this PR from master and that's why the commits looks funny. Could you rebase against develop?

**Comment by pobisw** [comment]
The merge is not resolving, so closing this and creating a fresh PR here 
#195

**Pull request closed without merging**
