### PR TITLE
Add Socket and HTTP listener options

### PR DESCRIPTION
**Pull request by jphenow**
Thoughts? Happy to alter and add tests, etc.

### CODE REVIEW

**Comment by jphenow** [comment]
To clarify a little,  I'm moving from my hand-written Middleware (which is very similar to this) which uses listeners to initialize DataLoaderContexts

**Comment by joemcbride** [comment]
I think this is essentially a duplicate of #61

**Comment by jphenow** [comment]
Ha! So it is. I didn't look close enough then. My bad! I'll close this. Thanks for glancing

**Comment by jphenow** [comment]
This is what I get for third-beer-in coding

**Pull request closed without merging**
