### PR TITLE
Pin playground to v1.7.28 and add polyfill for mutation events

### PR DESCRIPTION
**Pull request by Shane32**
Closes:
- #1158 

See:
- https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
- https://developer.chrome.com/blog/mutation-events-deprecation
- https://github.com/mfreed7/mutation-events-polyfill#readme
- https://www.npmjs.com/package/mutation-events

### CODE REVIEW

**Review by gao-artur — APPROVED** [review]
I don't really understand what you did here but OK 🙂

**Comment by Shane32** [comment]
@gao-artur I updated the PR description to more fully explain the changes.

**Comment by gao-artur** [comment]
@Shane32 I think this PR broke the autocomplete in the Playground.

**Comment by Shane32** [comment]
Well, it's not working properly now, but I must say, I think it was working even worse without this PR.  What do you propose?  Playground isn't supported and hasn't had a release in 5 years.  I'm not really interesting in investing time figuring out how to patch the javascript code.  My best suggestion is to mark all members as obsolete and release one final version, after which we remove the package from the solution.  I had hoped that by introducing the polyfill, it would start working properly again.  But it does not appear to have solved all the problems.

**Comment by gao-artur** [comment]
I'm fine with that. We will probably stop using it soon.

**Pull request merged**
